INSERT INTO fortnite_map.locations (id, name) VALUES (1, 'Junk Junction');
INSERT INTO fortnite_map.locations (id, name) VALUES (2, 'The Block');
INSERT INTO fortnite_map.locations (id, name) VALUES (3, 'Sunny Steps');
INSERT INTO fortnite_map.locations (id, name) VALUES (4, 'Haunted Hills');
INSERT INTO fortnite_map.locations (id, name) VALUES (5, 'Lazy Lagoon');
INSERT INTO fortnite_map.locations (id, name) VALUES (6, 'Pleasant Park');
INSERT INTO fortnite_map.locations (id, name) VALUES (7, 'Loot Lake');
INSERT INTO fortnite_map.locations (id, name) VALUES (8, 'Lonely Lodge');
INSERT INTO fortnite_map.locations (id, name) VALUES (9, 'Snobby Shores');
INSERT INTO fortnite_map.locations (id, name) VALUES (10, 'Dusty Divot');
INSERT INTO fortnite_map.locations (id, name) VALUES (11, 'Tilted Towers');
INSERT INTO fortnite_map.locations (id, name) VALUES (12, 'Retail Row');
INSERT INTO fortnite_map.locations (id, name) VALUES (13, 'Salty Springs');
INSERT INTO fortnite_map.locations (id, name) VALUES (14, 'Shifty Shafts');
INSERT INTO fortnite_map.locations (id, name) VALUES (15, 'Polar Peak');
INSERT INTO fortnite_map.locations (id, name) VALUES (16, 'Paradise Palms');
INSERT INTO fortnite_map.locations (id, name) VALUES (17, 'Fatal Fields');
INSERT INTO fortnite_map.locations (id, name) VALUES (18, 'Frosty Flights');
INSERT INTO fortnite_map.locations (id, name) VALUES (19, 'Happy Hamlet');
INSERT INTO fortnite_map.locations (id, name) VALUES (20, 'Lucky Landing');

INSERT INTO fortnite_map.items (id, lat, lng, type, location_id) VALUES (1, 1231.000000, 123.000000, 'CHEST', 11);
INSERT INTO fortnite_map.items (id, lat, lng, type, location_id) VALUES (2, 55.234000, 55.000000, 'CHEST', 1);
INSERT INTO fortnite_map.items (id, lat, lng, type, location_id) VALUES (3, 99.234000, 9999.000000, 'CHEST', 11);
INSERT INTO fortnite_map.items (id, lat, lng, type, location_id) VALUES (4, 3.100000, 4.000000, 'VENDING_MACHINE', null);
INSERT INTO fortnite_map.items (id, lat, lng, type, location_id) VALUES (5, 5.100000, 6.000000, 'VENDING_MACHINE', 11);
